[package]
name = "zmu_cortex_m"
version = "0.1.0"
authors = ["Jarmo Torvinen <jarmo.torvinen@iki.fi>"]
edition = "2021"

[dependencies]
byteorder = "1"
enum-set = "0.0.8"
gdbstub = "0.7"
gdbstub_arch = "0.3"


[features]
VFPSmallRegisterBank = []
armv6m = []
armv7m = ["VFPSmallRegisterBank"]
armv7em = ["VFPSmallRegisterBank"]
generic-device = []
stm32f103 = []